chore(infra): move to internal apps infra
camunda/int-haPDFy pull request #25
Opened 2024-02-08 10:33 UTC by polenz

related to #IN-270

2024-02-09 12:49 UTC, vringar requested changes
A couple of notes but overall this looks great!

2024-02-09 12:49 UTC, vringar commented on terraform/application/cloud_run.tf
> +  name     = "hapdfy"
```suggestion
  name     = "{var.prefix}hapdfy"
```
As both stage and live run in the same project all named resources need to have the prefix applied

2024-02-09 12:49 UTC, vringar commented on terraform/application/sa-cloud-run.tf
> +  account_id   = "hapdfy-sa"
```suggestion
  account_id   = "{var.prefix}hapdfy-sa"
```

2024-02-09 13:08 UTC, polenz commented on .github/workflows/deployer.yml
> +  PERFORM_CHANGES: ${{(github.ref == 'refs/heads/master' || github.ref == 'refs/heads/live') && github.event_name == 'push'}}
yes, that's right.

2024-02-12 11:29 UTC, vringar approved these changes

2024-02-12 11:50 UTC, merged